version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/home/python/app
      - ./.docker/zsh/history:/home/python/zsh:delegated

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
