# Generated by Django 4.2.11 on 2024-04-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_value',
            field=models.FloatField(default=100),
        ),
    ]
